version: "3.8"

services:
  pg:
    image: postgres:15
    container_name: symbx-pg
    environment:
      POSTGRES_USER: symbx
      POSTGRES_PASSWORD: symbx
      POSTGRES_DB: symbx
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symbx -d symbx"]
      interval: 5s
      timeout: 3s
      retries: 20

  minio:
    image: minio/minio:latest
    container_name: symbx-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: symbx
      MINIO_ROOT_PASSWORD: replicax12345
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - miniodata:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
  miniodata:
